"""add created_by_id to tasks

Revision ID: 9a82d1647a16
Revises: 96e734feae04
Create Date: 2026-03-27 12:37:49.640003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a82d1647a16'
down_revision: Union[str, None] = '96e734feae04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_tasks_created_by_id', ['created_by_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_created_by_id_users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_created_by_id_users', type_='foreignkey')
        batch_op.drop_index('ix_tasks_created_by_id')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
